export const GET_POKEMON = "GET_POKEMON";
export const GET_POKEMON_DETAIL = "GET_POKEMON_DETAIL";
export const GET_POKEMON_EVOLUTION = "GET_POKEMON_EVOLUTION";
export const GET_POKEMON_SPECIES = "GET_POKEMON_SPECIES";
